version: "3.7"
services:
  app:
    build:
      args:
        user: rafael
        uid: 197602
      context: ./
      dockerfile: Dockerfile
    image: usapp
    container_name: usapp-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - usapp

  db:
    image: mysql:5.7
    container_name: usapp-db
    restart: unless-stopped
    ports:
      - 33071:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - usapp

  nginx:
    image: nginx:alpine
    container_name: usapp-nginx
    restart: unless-stopped
    ports:
      - 7001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - usapp

  redis:
    image: redis
    container_name: usapp-redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - usapp
networks:
  usapp:
    driver: bridge